# Generated by Django 4.1.7 on 2023-02-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_federal_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_state_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('self_employment_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('federal_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('local_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
